[2025-07-25T00:26:42.043+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-24T00:00:00+00:00 [queued]>
[2025-07-25T00:26:42.097+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-24T00:00:00+00:00 [queued]>
[2025-07-25T00:26:42.099+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-25T00:26:42.200+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_from_minio> on 2025-07-24 00:00:00+00:00
[2025-07-25T00:26:42.238+0000] {standard_task_runner.py:60} INFO - Started process 25997 to run task
[2025-07-25T00:26:42.254+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sales_batch_etl', 'load_from_minio', 'scheduled__2025-07-24T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/sales_batch_etl.py', '--cfg-path', '/tmp/tmp1jk_3i3d']
[2025-07-25T00:26:42.265+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask load_from_minio
[2025-07-25T00:26:42.341+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-25T00:26:42.387+0000] {task_command.py:423} INFO - Running <TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-24T00:00:00+00:00 [running]> on host e17dc2585651
[2025-07-25T00:26:42.484+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_batch_etl' AIRFLOW_CTX_TASK_ID='load_from_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T00:00:00+00:00'
[2025-07-25T00:26:42.487+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-25T00:26:42.490+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/load_from_minio.py']
[2025-07-25T00:26:42.505+0000] {subprocess.py:86} INFO - Output:
[2025-07-25T00:26:43.845+0000] {subprocess.py:93} INFO - ‚è≥ Connecting to MinIO...
[2025-07-25T00:26:43.855+0000] {subprocess.py:93} INFO - üì• Downloading 'sales.csv' from bucket 'raw'
[2025-07-25T00:26:43.855+0000] {subprocess.py:93} INFO - ‚úÖ Downloaded data with shape: (10000, 6)
[2025-07-25T00:26:43.855+0000] {subprocess.py:93} INFO - üìÅ Data saved to /tmp/sales.csv
[2025-07-25T00:26:43.907+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-25T00:26:43.977+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=sales_batch_etl, task_id=load_from_minio, execution_date=20250724T000000, start_date=20250725T002642, end_date=20250725T002643
[2025-07-25T00:26:44.039+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-25T00:26:44.089+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
