[2025-07-17T00:25:52.602+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-17T00:25:52.608+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-17T00:25:52.608+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-17T00:25:52.616+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_from_minio> on 2025-07-16 00:00:00+00:00
[2025-07-17T00:25:52.628+0000] {standard_task_runner.py:60} INFO - Started process 2477 to run task
[2025-07-17T00:25:52.637+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sales_batch_etl', 'load_from_minio', 'scheduled__2025-07-16T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/sales_batch_etl.py', '--cfg-path', '/tmp/tmpbt942fif']
[2025-07-17T00:25:52.640+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask load_from_minio
[2025-07-17T00:25:52.662+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-17T00:25:52.716+0000] {task_command.py:423} INFO - Running <TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-16T00:00:00+00:00 [running]> on host e17dc2585651
[2025-07-17T00:25:52.815+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_batch_etl' AIRFLOW_CTX_TASK_ID='load_from_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T00:00:00+00:00'
[2025-07-17T00:25:52.820+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-17T00:25:52.822+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/load_from_minio.py']
[2025-07-17T00:25:52.838+0000] {subprocess.py:86} INFO - Output:
[2025-07-17T00:25:55.114+0000] {subprocess.py:93} INFO - ‚è≥ Connecting to MinIO...
[2025-07-17T00:25:55.125+0000] {subprocess.py:93} INFO - üì• Downloading 'sales.csv' from bucket 'raw'
[2025-07-17T00:25:55.126+0000] {subprocess.py:93} INFO - ‚úÖ Downloaded data with shape: (10000, 6)
[2025-07-17T00:25:55.126+0000] {subprocess.py:93} INFO - üìÅ Data saved to /tmp/sales.csv
[2025-07-17T00:25:55.248+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-17T00:25:55.338+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=sales_batch_etl, task_id=load_from_minio, execution_date=20250716T000000, start_date=20250717T002552, end_date=20250717T002555
[2025-07-17T00:25:55.382+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-17T00:25:55.439+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
