[2025-07-16T07:49:32.888+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio manual__2025-07-16T07:49:31.504361+00:00 [queued]>
[2025-07-16T07:49:32.893+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio manual__2025-07-16T07:49:31.504361+00:00 [queued]>
[2025-07-16T07:49:32.893+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-16T07:49:32.899+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_from_minio> on 2025-07-16 07:49:31.504361+00:00
[2025-07-16T07:49:32.903+0000] {standard_task_runner.py:60} INFO - Started process 3955 to run task
[2025-07-16T07:49:32.905+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sales_batch_etl', 'load_from_minio', 'manual__2025-07-16T07:49:31.504361+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/sales_batch_etl.py', '--cfg-path', '/tmp/tmpx2clln1e']
[2025-07-16T07:49:32.907+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask load_from_minio
[2025-07-16T07:49:32.934+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-16T07:49:32.970+0000] {task_command.py:423} INFO - Running <TaskInstance: sales_batch_etl.load_from_minio manual__2025-07-16T07:49:31.504361+00:00 [running]> on host 475ab637e9bf
[2025-07-16T07:49:33.021+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_batch_etl' AIRFLOW_CTX_TASK_ID='load_from_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T07:49:31.504361+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-16T07:49:31.504361+00:00'
[2025-07-16T07:49:33.022+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-16T07:49:33.022+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/load_from_minio.py']
[2025-07-16T07:49:33.029+0000] {subprocess.py:86} INFO - Output:
[2025-07-16T07:49:33.423+0000] {subprocess.py:93} INFO - ‚è≥ Connecting to MinIO...
[2025-07-16T07:49:33.424+0000] {subprocess.py:93} INFO - üì• Downloading 'sales.csv' from bucket 'raw'
[2025-07-16T07:49:33.425+0000] {subprocess.py:93} INFO - ‚úÖ Downloaded data with shape: (3, 6)
[2025-07-16T07:49:33.425+0000] {subprocess.py:93} INFO - üìÅ Data saved to /tmp/sales.csv
[2025-07-16T07:49:33.466+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-16T07:49:33.490+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=sales_batch_etl, task_id=load_from_minio, execution_date=20250716T074931, start_date=20250716T074932, end_date=20250716T074933
[2025-07-16T07:49:33.507+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-16T07:49:33.520+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
