[2025-07-16T07:53:08.962+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio manual__2025-07-16T07:48:06.691375+00:00 [queued]>
[2025-07-16T07:53:08.966+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio manual__2025-07-16T07:48:06.691375+00:00 [queued]>
[2025-07-16T07:53:08.967+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-16T07:53:08.973+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_from_minio> on 2025-07-16 07:48:06.691375+00:00
[2025-07-16T07:53:08.977+0000] {standard_task_runner.py:60} INFO - Started process 4038 to run task
[2025-07-16T07:53:08.981+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sales_batch_etl', 'load_from_minio', 'manual__2025-07-16T07:48:06.691375+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/sales_batch_etl.py', '--cfg-path', '/tmp/tmp9q7vwq19']
[2025-07-16T07:53:08.982+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask load_from_minio
[2025-07-16T07:53:08.996+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-16T07:53:09.027+0000] {task_command.py:423} INFO - Running <TaskInstance: sales_batch_etl.load_from_minio manual__2025-07-16T07:48:06.691375+00:00 [running]> on host 475ab637e9bf
[2025-07-16T07:53:09.076+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_batch_etl' AIRFLOW_CTX_TASK_ID='load_from_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T07:48:06.691375+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-16T07:48:06.691375+00:00'
[2025-07-16T07:53:09.077+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-16T07:53:09.078+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/load_from_minio.py']
[2025-07-16T07:53:09.085+0000] {subprocess.py:86} INFO - Output:
[2025-07-16T07:53:09.484+0000] {subprocess.py:93} INFO - ‚è≥ Connecting to MinIO...
[2025-07-16T07:53:09.484+0000] {subprocess.py:93} INFO - üì• Downloading 'sales.csv' from bucket 'raw'
[2025-07-16T07:53:09.485+0000] {subprocess.py:93} INFO - ‚úÖ Downloaded data with shape: (3, 6)
[2025-07-16T07:53:09.485+0000] {subprocess.py:93} INFO - üìÅ Data saved to /tmp/sales.csv
[2025-07-16T07:53:09.526+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-16T07:53:09.545+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=sales_batch_etl, task_id=load_from_minio, execution_date=20250716T074806, start_date=20250716T075308, end_date=20250716T075309
[2025-07-16T07:53:09.575+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-16T07:53:09.589+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
